### ISSUE TITLE
Accept chroma credentials from environment variables, e.g.: ENV CHROMA_ADMIN_DATABASE_URL

### ISSUE THREAD

**Issue by jannikhst** [flanker/chromadb-admin#6]
For the dockerized version of this admin client it would be nice if we can predefine the credentials for the db within the docker compose file. Here would be the use case (see last line of code):

```
  chroma:
    image: chromadb/chroma:latest
    restart: always
    container_name: chroma
    networks:
      - internal_network
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -f localhost:8000/api/v1/heartbeat || exit 1"
        ]
      interval: 20s
      timeout: 30s
      retries: 5
    environment:
      CHROMA_SERVER_AUTH_CREDENTIALS: password
      CHROMA_SERVER_AUTH_CREDENTIALS_PROVIDER: chromadb.auth.token.TokenConfigServerAuthCredentialsProvider
      CHROMA_SERVER_AUTH_PROVIDER: chromadb.auth.token.TokenAuthServerProvider

  chroma-db-admin:
    image: fengzhichao/chromadb-admin
    container_name: chroma-db-admin
    depends_on:
      chroma:
        condition: service_healthy
    restart: always
    networks:
      - traefik_web
      - internal_network
    ports:
      - 3001:3000
    environment:
      CHROMA_ADMIN_DATABASE_URL: http://chroma:8000?authProvider=TokenAuthServerProvider&token=password
```

Setting this environment variable would then skip the login screen when visiting http://localhost:3001

Thanks in advance!
